### ISSUE TITLE
Disable quick suggestion

### ISSUE THREAD

**Issue by davingreen** [gladed/linkist#3]
I was really enjoying using this! But, I've got to disable it because it seems to be interfering with https://github.com/kortina/vscode-markdown-notes. When this plugin is enabled, quick suggestions and suggestions do not show any other options (besides linkist links). I need to be able to see other suggestions. For example, if I need to insert a wiki style link [[File]], this triggers the liskist quick suggest and prevents seeing the available files.

**Comment by GladeDiviney** [comment]
Thanks! This can be made into an option.

**Comment by gladed** [comment]
This is fixed in [v1.4.9](https://github.com/gladed/linkist/releases/tag/v1.4.9). The autocomplete code is smarter and stops suggesting completions when you type `[[`.
