### ISSUE TITLE
Enable hash links (for same name, same link)

### ISSUE THREAD

**Issue by davingreen** [gladed/linkist#4]
Just a suggestion!

I would love the option to enable links that are small hashes of their original header. This would be particularly useful for dates --

Create a link from string "2020-09-05" and get a hash "aBcD". This has is the same for any links created on string "2020-09-15", so all can be linked.

**Comment by gladed** [comment]
This is a good idea. Link IDs are an almalgam of date and a counter (not a hash). But I could do a case-insensitive search for a link with the same names and just use its ID.

**Comment by gladed** [comment]
This is fixed in [v1.4.9](https://github.com/gladed/linkist/releases/tag/v1.4.9). If you select text and link it, it will automatically take the same link ID if that same text is linked elsewhere.
