### ISSUE TITLE
Same link created for different selection

### ISSUE THREAD

**Issue by davingreen** [gladed/linkist#5]
![image](https://user-images.githubusercontent.com/11077948/94378090-86e35e00-00f4-11eb-8dde-71301ff87c21.png)

Two headers with similar, but different text are generating the same link location.

**Comment by gladed** [comment]
Looking into this, thanks for the report.

**Comment by gladed** [comment]
I am not able to reproduce this. Can you give me exact steps to get here?

**Comment by davingreen** [comment]
I can't reproduce it now either! Must have been a unique situation -- sorry for the false alarm!
