### ISSUE TITLE
Backlinks window in explorer

### ISSUE THREAD

**Issue by gladed** [gladed/linkist#8]
Show:

* Links pointing into the current section
* Links pointing into parents of the current section
* Links pointing into the same file
* Links created on the same or similar days as the current link (under cursor, or in section, or in parent)

**Comment by GladeDiviney** [comment]
* Hit link on a heading and you'll see links pointing to current link.
* Ctrl+Space on a heading and you'll see "Created 2020-02-20".

This is enough for now without a lot of fancy reporting.
